lst=[]
a=input("enter roll number :")
b=input("enter name :")
c=input("enter age of student :")
a1=tuple(a)
lst.append(a1)
b1=tuple(b)
lst.append(b1)
c1=tuple(c)
lst.append(c1)
print(lst)
lst1=list(lst[0])
print(lst1)
lst2=list(lst[1])
print(lst2)
lst3=list(lst[2])
print(lst3)
